# ---- General ----

unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

set -g prefix C-s

set -g mouse on
set -g focus-events on

set -g history-limit 10000

# True color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",$TERM:Tc"

# ---- Pane navigation (vim) ----
unbind h
unbind j
unbind k
unbind l
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Splits
bind | split-window -h
bind - split-window -v

# ---- Appearance ----
set -g status-interval 1
set -g status-position bottom
set -g status-style bg=default

set -g status-left "#[fg=#cdcdcd,bg=#252530] #S "
set -g status-left-length 40
set -g status-right " #[fg=#cdcdcd,bg=#252530] %H:%M  %d %b "
set -g status-right-length 40

set -g window-status-separator " "
set -g window-status-format "#[fg=#252530,bg=#d7d7d7] #I #[fg=#cdcdcd,bg=#252530] #W "
set -g window-status-current-format "#[fg=#252530,bg=#f3be7c] #I #[fg=#cdcdcd,bg=#252530] #W "
set -g window-status-current-style bg=default

set -g message-style "fg=#252530,bg=#aeaed1"
set -g pane-border-style "fg=#606079"
set -g pane-active-border-style "fg=#878787"
