# ---- Appearance ----

set -g status on
set -g status-interval 1
set -g status-left-length 40
set -g status-right-length 40
set -g status-style "fg=white"

set -g message-style "fg=black,bg=cyan"

set -g window-status-separator ""

set -g status-left "#[fg=white,bg=#252530] #S "

set -g status-right "#[fg=white] %d %b  %H:%M #{tmux_mode_indicator}"
setw -g window-status-format "#[fg=black,bg=white] #I #[fg=white,bg=#252530] #W#{?window_flags,#[fg=yellow]#{window_flags},} "
setw -g window-status-current-format "#[fg=black,bg=yellow] #I #[fg=white,bg=#252530] #W#{?window_flags,#[fg=yellow]#{window_flags},} "
