# ---- General ----
set -g prefix C-s
bind C-s send-prefix

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g mouse on
set -g focus-events on
set -sg escape-time 0
set -g history-limit 50000
setw -g mode-keys vi

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."
bind x kill-pane

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
set -as terminal-features ",*:hyperlinks"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g set-clipboard on
set -g allow-passthrough all

# ---- Pane Navigation ----

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h resize-pane -L
bind -r C-j resize-pane -D
bind -r C-k resize-pane -U
bind -r C-l resize-pane -R

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# ---- Copy Mode ----

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ---- Plugins ----

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'MunifTanjim/tmux-mode-indicator'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# # ---- Appearance ----
source-file ~/.config/tmux/appearance.conf

run '~/.config/tmux/plugins/tpm/tpm'
