# ---- General ----
set -g prefix C-s
bind C-s send-prefix
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

set -g base-index 1
set -g renumber-windows on
setw -g pane-base-index 1

set -g set-titles on
set -g set-titles-string "#S:#I - #W"

set -g mouse on
set -g focus-events on
set -sg escape-time 0
set -g history-limit 50000
set -g set-clipboard on
set -g allow-passthrough all
set -g extended-keys on
set -g extended-keys-format csi-u
setw -g mode-keys vi

# ---- Terminal ----
set -g default-terminal "tmux-256color"
set -su terminal-features
set -as terminal-features ",*:RGB"
set -as terminal-features ",*:hyperlinks"
set -su terminal-overrides
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# ---- Panes & Windows ----
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h resize-pane -L
bind -r C-j resize-pane -D
bind -r C-k resize-pane -U
bind -r C-l resize-pane -R

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind G popup -E -d "#{pane_current_path}" -w 80% -h 90% lazygit
bind x kill-pane

# ---- Copy Mode ----
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# ---- Appearance ----
set -s theme terminal
set -g status on
set -g status-interval 5
set -g status-left-length 40
set -g status-right-length 40
set -g status-style "fg=white"

set -g message-style "fg=black,bg=cyan,fill=cyan"

set -g popup-style "bg=default,fg=default"
set -g popup-border-style "bg=default,fg=white"

set -g window-status-separator ""
setw -g fill-character ""
setw -g window-status-current-style default

set -g status-left "#[fg=white,bg=#252530] #S "

set -g status-right "#[fg=black]#{?client_prefix,#[bg=blue] WAIT ,#{?pane_in_mode,#[bg=yellow] COPY ,#{?pane_synchronized,#[bg=red] SYNC ,#[bg=cyan] TMUX }}}#[default]"
setw -g window-status-format "#[fg=black,bg=white] #I #[fg=white,bg=#252530] #W#{?window_flags,#[fg=yellow]#{window_flags},} "
setw -g window-status-current-format "#[fg=black,bg=yellow] #I #[fg=white,bg=#252530] #W#{?window_flags,#[fg=yellow]#{window_flags},} "
