Set-Alias vim nvim
Set-Alias open explorer
Set-Alias ls Get-ChildItemFormatted
Set-Alias ll Get-ChildItemFormatted
Set-Alias touch New-File
Set-Alias grep Find-String
Set-Alias cat bat
Set-Alias which Get-CommandDefinition
Set-Alias nah Reset-GitChanges
Set-Alias glog Get-GitLog
Set-Alias art Invoke-LaravelArtisan
Set-Alias us Update-SystemSoftware
Set-Alias lg lazygit
Set-Alias rmrf Remove-ItemForceRecursive
Set-Alias opencode Invoke-OpenCodeWSL
Set-Alias su Update-ShellElevation
Set-Alias oc opencode
